---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 10m
  url: https://metallb.github.io/metallb
  timeout: 1m
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: longhorn
  namespace: flux-system
spec:
  interval: 10m
  url: https://charts.longhorn.io
  timeout: 1m
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: jetstack-charts
  namespace: flux-system
spec:
  interval: 10m
  url: https://charts.jetstack.io/
  timeout: 1m
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: godaddy-webhook
  namespace: flux-system
spec:
  interval: 10m
  url: https://fred78290.github.io/cert-manager-webhook-godaddy/
  timeout: 1m
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: k8s-at-home-charts
  namespace: flux-system
spec:
  interval: 10m
  url: https://k8s-at-home.com/charts/
  timeout: 1m
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: emqx-charts
  namespace: flux-system
spec:
  interval: 10m
  url: https://repos.emqx.io/charts
  timeout: 1m