---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 5m
  chart:
    spec:
      chart: longhorn
      version: 1.3.2
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
      interval: 5m
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
