---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 5m
  chart:
    spec:
      chart: metallb
      version: 0.13.7
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
      interval: 5m
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    configInline:
      address-pools:
      - name: default
        protocol: layer2
        addresses:
        - 192.168.10.48-192.168.10.63