---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: emqx
  namespace: emqx
spec:
  interval: 5m
  chart:
    spec:
      chart: emqx
      version: 5.0.11
      sourceRef:
        kind: HelmRepository
        name: emqx-charts
        namespace: flux-system
      interval: 5m
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  timeout: 20m
  values:
    image:
      repository: emqx/emqx
    replicaCount: 3
    recreatePods: true
    service:
      loadBalancerIP: 192.168.10.49
      type: LoadBalancer
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
              - emqx
          topologyKey: "kubernetes.io/hostname"
    emqxConfig:
      EMQX_AUTHENTICATION__1__MECHANISM: "password_based"
      EMQX_AUTHENTICATION__1__BACKEND: "built_in_database"
      EMQX_AUTHENTICATION__1__USER_ID_TYPE: "username"
      EMQX_AUTH__USER__1__USERNAME: tasmota
      EMQX_AUTH__USER__2__USERNAME: test
      EMQX_AUTH__USER__2__PASSWORD: test
    resources:
      limits:
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi
    ingress:
      dashboard:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
        path: /
        hosts:
        - emqx.myhaus.co.za
        tls:
        - hosts:
          - emqx.myhaus.co.za
  valuesFrom:
  - kind: Secret
    name: "emqx-helm-values"
    optional: false