---
apiVersion: v1
kind: ConfigMap
metadata:
  name: emqx-create-users
  namespace: emqx
data:
  create-users: |
    RESPONSE=`curl -s "http://admin:$EMQX_DASHBOARD__DEFAULT_PASSWORD@emqx-headless:18083/api/v5/authentication/password_based:built_in_database/users" -H 'Content-Type: application/json' -d '{"user_id":"'"$EMQX_AUTH__USER__1__USERNAME"'","password":"'"$EMQX_AUTH__USER__1__PASSWORD"'"}'`
    echo $RESPONSE
    if [[ "$RESPONSE" == *"tasmota"* || "$RESPONSE" == *"User already exists"* ]]; then
      exit 0
    fi
    exit 1
---
apiVersion: batch/v1
kind: Job
metadata:
  name: emqx-create-users
  namespace: emqx
spec:
  backoffLimit: 4
  completions: 1
  parallelism: 1
  template:
    spec:
      containers:
      - command: ["sh", "/create-users"]
        envFrom:
        - configMapRef:
            name: emqx-env
        image: curlimages/curl
        imagePullPolicy: IfNotPresent
        name: emx-create-users
        volumeMounts:
          - name: emqx-create-users
            mountPath: /create-users
            subPath: create-users
      restartPolicy: Never
      volumes:
        - name: emqx-create-users
          configMap:
            name: emqx-create-users