# Runs a job that registers a user the first time EMQX comes up.
# It uses the old EMQX_AUTH__USER__1__USERNAME and EMQX_AUTH__USER__1__PASSWORD
# environment variables that EMQX used to use to register users.
# We might need to extend this script if we ever need more users to be bootstrapped.
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: emqx-create-users
  namespace: emqx
data:
  create-users: |
    RESPONSE=`curl -s "http://admin:$EMQX_DASHBOARD__DEFAULT_PASSWORD@emqx-headless:18083/api/v5/authentication/password_based:built_in_database/users" -H 'Content-Type: application/json' -d '{"user_id":"'"$EMQX_AUTH__USER__1__USERNAME"'","password":"'"$EMQX_AUTH__USER__1__PASSWORD"'"}'`
    echo $RESPONSE
    if [[ "$RESPONSE" == *"$EMQX_AUTH__USER__1__USERNAME"* || "$RESPONSE" == *"User already exists"* ]]; then
      exit 0
    fi
    exit 1
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: emqx-create-users
spec:
  concurrencyPolicy: Forbid
  schedule: "0 0 * * *"
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      activeDeadlineSeconds: 300
      backoffLimit: 3
      ttlSecondsAfterFinished: 60
      template:
        metadata:
          name: emqx-create-users
        spec:
          containers:
          - command: ["sh", "/create-users"]
            envFrom:
            - configMapRef:
                name: emqx-env
            image: curlimages/curl
            imagePullPolicy: IfNotPresent
            name: emx-create-users
            volumeMounts:
              - name: emqx-create-users
                mountPath: /create-users
                subPath: create-users
          restartPolicy: Never
          volumes:
            - name: emqx-create-users
              configMap:
                name: emqx-create-users
---
apiVersion: batch/v1
kind: Job
metadata:
  name: emqx-create-users
  namespace: emqx
spec:
  backoffLimit: 4
  completions: 1
  parallelism: 1
  template:
    spec:
      containers:
      - command: ["sh", "/create-users"]
        envFrom:
        - configMapRef:
            name: emqx-env
        image: curlimages/curl
        imagePullPolicy: IfNotPresent
        name: emx-create-users
        volumeMounts:
          - name: emqx-create-users
            mountPath: /create-users
            subPath: create-users
      restartPolicy: Never
      volumes:
        - name: emqx-create-users
          configMap:
            name: emqx-create-users
