apiVersion: v1
kind: Secret
metadata:
    name: godaddy-api-key-prod
    namespace: cert-manager
type: Opaque
data:
    key: ENC[AES256_GCM,data:0DPnYI0i8dUUS5Dgt7x00ONG7HHFvVWwGKcloTqp6OwIx1SpOmuvgaikBG4KwBOf,iv:OVmu8X9T0uQd1PzqI2mQFq4lJAtab4JBumqwOfT+LIE=,tag:EBz/JbVPkB26m3+cdfWOew==,type:str]
    secret: ENC[AES256_GCM,data:Y75nvD46ayrkA/qgfV6y7bcqHnZMVU6inhLvz0fz6Uc=,iv:0qDH3v4pyC6k8mxWWd0TT4PHNybKLVjEoLA0nlRxU68=,tag:yGkHv+I6RMOtMK7PsdX8eA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-12-11T18:04:27Z"
    mac: ENC[AES256_GCM,data:K/xCiI8mUMpsGaPv1oMbZ/p7hqMqFj2pQ7HKV3WU9suOwT7xm2jpnD23WLm2SyR1m3AmDEl8mV12ZcdVwIXFXo/bmNiTwrzU7lFz6dyx77ZsW/KcwFMd8d7KJuogAtDDWMeAdUjDPNsfdSBOIJJgTU+JFQwoM1wtTpNChX6nTHc=,iv:hDg4+ck8aGjLRaGUoaetiyyB8hc6S82GDuNxERdmqQk=,tag:khh4oDegvdqFQKPwZZwSPg==,type:str]
    pgp:
        - created_at: "2022-12-11T18:04:26Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMAwOBBeOnrR8mAQv/ZxtqkcRzWR8OFx/i0SJM0m3ooXdyvRAl9cvz+M8FHOXT
            mQsPYZKBLC7yeluv6OU84kr0tgIRx51mGUP7lUuTE7aVF6kHNkG6nu/0jG4hlk7O
            IH3GIJ/5uc+ITZvYs6UrDlyoS7d2VqoR3daWR5rFgfPWpPSKHcR+3vkPZDha6q/+
            Lkh0llhjpY53RktghnLgD1qWrx/ecjfJH43S4mvDpuGi7lGf+ZG8n7YPgmRWlZyM
            +kGBaX3D0RHPmR5eK85YAxINUrMtpOo2WrfWDxRzSeVS7AzORlL4hAFPpwf3lE5s
            gjqzVv4hLGpeg2y0NcBXUzqQt7xRX+AI1XpvItBILbzS5sjK1WjhDKywyoTmpCob
            d6jTdfTJ6pOfT7whPZhduia4dJIAIB55PKtFqkIIYXD5ntLo3swrh+sjdc6fxaIN
            BjnXP+pdt3uq8bkErrn1KrcyoBwzgFl5O+Sy8Jjux/RL7IIVRgdDbUdDBwoiStmc
            iBOSKPF03hDBJ2yO6L1w0l4BxS1Y86U+t4sVeATtiASc06+MM1OiralZ3tTQW3k8
            9KEYMx2XxsWEW1TrS3pukmUMMCByeUxRc/AFxAoXfTx3DvQwLPq10B12YRf1JK+m
            PGHkUTUMbU5ZTZUKI8ip
            =sMkD
            -----END PGP MESSAGE-----
          fp: 571FF0B5C64828FEA4CACDCD5728C37710565246
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
