apiVersion: v1
kind: PersistentVolume
metadata:
 name: home-assistant
 labels:
   app: home-assistant
   type: nfs
spec:
 capacity:
   storage: 10Gi
 accessModes:
   - ReadWriteMany
 persistentVolumeReclaimPolicy: Retain
 nfs:
   server: "192.168.1.21"
   path: "/mnt/tank/kubernetes/home-assistant"