apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: home-assistant
spec:
 storageClassName: ""
 accessModes:
   - ReadWriteMany
 resources:
   requests:
     storage: 10Gi
 selector:
   matchLabels:
     app: home-assistant
     type: nfs