apiVersion: v1
kind: Service
metadata:
  name: home-assistant
spec:
  selector:
    app.kubernetes.io/name: home-assistant
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8123
  type: LoadBalancer
