apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: home-assistant
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: home-assistant
  serviceName: "home-assistant"
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: home-assistant
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - env:
          - name: TZ
            value: "Africa/Johannesburg"
          name: home-assistant
          image: homeassistant/home-assistant:2022.12.4
          ports:
            - containerPort: 8123
          volumeMounts:
            - mountPath: "/config"
              name: config
  volumeClaimTemplates:
  - metadata:
      name: home-assistant
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "longhorn"
      resources:
        requests:
          storage: 10Gi
